services:
  backend:
    build: ./server
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
    networks:
      - fullstack
    volumes:
      - ./server:/app
    command: "node index.js"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000"]
      interval: 5s
      retries: 10

  frontend:
    build: ./client
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - fullstack
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - HOST=0.0.0.0
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0"]

networks:
  fullstack:
    driver: bridge
